### ISSUE TITLE
Webpacker doesn't compile with Tailwind 2

### ISSUE THREAD

**Issue by dalton-cole** [justalever/kickoff_tailwind#14]
When building from the template, it installs Tailwind ^2.1 which causes a webpacker compilation error. 

`The `rounded` class does not exist. If you're sure that `rounded` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.`

**Comment by dalton-cole** [comment]
Updating dependencies with `"tailwindcss": "^1.9.2"` seems to work.

**Comment by justalever** [comment]
I just merged in support for this now. Should be able to run Tailwind 2.0 as well!
