### ISSUE TITLE
When I clone the repo I started seeing sidekiq spam in foreman

### ISSUE THREAD

**Issue by spacerobotTR** [justalever/kickoff_tailwind#8]
All of a sudden when I create a new project from the template and first start it up I see this over and over in foreman:

13:47:19 sidekiq.1 | `Redis#exists(key)` will return an Integer in redis-rb 4.3, if you want to keep the old behavior, use `exists?` instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer = true. (/Users/apple/.rvm/gems/ruby-2.6.3/gems/sidekiq-6.0.7/lib/sidekiq/launcher.rb:160:in `block (2 levels) in ❤')

Any idea what this is? It wasn't doing this before.

**Comment by justalever** [comment]
I think it's relative to your ruby version + Redis. It's probably safe to ignore for now
